language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -t ./...
  - export CGO_ENABLED=0

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v ./... -coverprofile=coverage.text -covermode=count
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)